Add ability to list company associations
belong-inc/go-hubspot pull request #27
Opened 2023-12-18 10:12 UTC by joidegn

## What to do  
Adds the ability to GET company associations

https://developers.hubspot.com/docs/api/crm/associations

## Background  
This was previously not possible yet

## Acceptance criteria  
The user can GET company associations with other objects

2024-01-11 07:06 UTC, kk-no requested changes
@joidegn 
Sorry for my late reply...
I merged Unmarshal bugfix #29 and added comments to this PR.

thank you!

2024-01-11 08:06 UTC, kk-no commented on association.go
> +type AssocationType struct {
Not used?

2024-01-11 08:08 UTC, kk-no commented on company.go
> +	GetAssociations(companyID, toObjectType string, result *AssociationsResponse) (*AssociationsResponse, error)
Is it possible to use type of `ObjectType` for toObjectType?

2024-01-11 08:15 UTC, kk-no commented on company.go
> +func (s *CompanyServiceOp) GetAssociations(companyID, toObjectType string, result *AssociationsResponse) (*AssociationsResponse, error) {
> The Associations API /crm/v4/objects/{objectType}/{objectId}/associations/{toObjectType} only works with HubSpot API v4, while go-hubspot, which uses the default version, is v3.
Could you add a comment like "This method only works with HubSpot API v4."

There is no mention in the v3 documentation, but it worked in my hands... Comments may not be necessary.

2024-01-18 11:38 UTC, joidegn commented on company.go
> +func (s *CompanyServiceOp) GetAssociations(companyID, toObjectType string, result *AssociationsResponse) (*AssociationsResponse, error) {
Unless Im mixing things up this does use /crm/v3 endpoint. This is why Im saying that I believe this endpoint is not documented. It does seem to work for me even though I also was not able to find documentation for it.

I.e. the address used is `/crm/v3/objects/{objecyType}/{objectId}/associations/{toObjectType}`

2024-01-18 11:38 UTC, joidegn commented on company.go
> +func (s *CompanyServiceOp) GetAssociations(companyID, toObjectType string, result *AssociationsResponse) (*AssociationsResponse, error) {
Ah sorry, yeah you said that further down! 👍

2024-01-18 15:00 UTC, joidegn commented
Sorry it took so long. I think I have revised the PR as you proposed.

2024-01-23 01:25 UTC, kk-no reviewed
Looks good to me!
It seems that only company_model.go has the previous modification left, so could you please check it again?

2024-01-23 01:25 UTC, kk-no commented on company_model.go
I thought I could unmarshal to `HsInt` using https://github.com/belong-inc/go-hubspot/pull/29, but is this necessary?

2024-02-01 02:38 UTC, kk-no commented
Hi, @joidegn !
We plan to create a new version next week.
I would like to include this PR if possible, but did you check the PR comments?

2024-12-13 23:39 UTC, andrewrynhard commented
Is this going to make it in?

2025-01-21 02:42 UTC, kk-no commented
@joidegn 
How about after that?
We are considering closing PR and then implementing the feature on our end.

2025-02-17 00:29 UTC, closed without merging