Add client of Marketing domain to handle marketing email statistics
belong-inc/go-hubspot pull request #6
Opened 2022-05-13 02:11 UTC by ttyfky

- Add marketing service
- Add API of marketing email statistics
- Add legacy package to handle HubSpot API v1 context
- Add doc.go in the root and legacy package

2022-05-13 02:35 UTC, ttyfky commented on example_test.go
> +	cli, _ := hubspot.NewClient(hubspot.SetAPIKey(os.Getenv("API_KEY")))
Made apikey to env var to prevent upload real apikey after testing.

2022-05-16 06:45 UTC, kk-no commented
Marketingの分のテストはどのタイミングで足しますか？(後で僕の方で足すでも大丈夫です)

2022-05-16 06:47 UTC, kk-no requested changes
いくつかコメントしました
(構造体のフィールド名は自動生成だと思うので特に付けてません)

2022-05-16 06:47 UTC, kk-no commented on legacy/marketing_emails.go
> +type marketingEmaiHelperOp struct {
```suggestion
type marketingEmailHelperOp struct {
```
typo

2022-05-16 06:47 UTC, kk-no commented on marketing_email.go
> +func (m MarketingEmailOp) ListStatistics(resource interface{}, option *RequestQueryOption) (*ResponseResource, error) {
```suggestion
func (m *MarketingEmailOp) ListStatistics(resource interface{}, option *RequestQueryOption) (*ResponseResource, error) {
```
特に理由なければレシーバはポインタで揃えたいです

2022-05-16 06:47 UTC, kk-no commented on marketing_email.go
> +func (m *MarketingEmailOp) GetStatistics(emailID int, resource interface{}, option *RequestQueryOption) (*ResponseResource, error) {
```suggestion
func (m *MarketingEmailOp) GetStatistics(emailID int, resource interface{}) (*ResponseResource, error) {
	if err := m.client.Get(m.legacyAPIHelper.GetStatisticsPath()+fmt.Sprintf("/%d", emailID), resource, nil); err != nil {
```
option.setupPropertiesは取得するプロパティをクエリパラメータで指定するためのもので、このAPIは一括で全フィールド取得しそうなので不要だと思います。
https://legacydocs.hubspot.com/docs/methods/cms_email/get-the-statistics-for-a-marketing-email

2022-05-16 06:47 UTC, kk-no commented on marketing_email.go
> +func (m MarketingEmailOp) ListStatistics(resource interface{}, option *RequestQueryOption) (*ResponseResource, error) {
RequestQueryOptionが汎用的な名前になってしまってますが、このエンドポイントでは Limit/Offset/Orderby だけしか使わないっぽいので新しく Option 構造体を作るか FIXME コメントあたりを残して貰えると助かります
https://legacydocs.hubspot.com/docs/methods/cms_email/get-all-marketing-email-statistics

2022-05-16 06:52 UTC, kk-no commented
あとついでに README.md  の Available list も更新して貰えると助かります。。

2022-05-16 07:47 UTC, ttyfky reviewed
- Fixed the code as per comment
- Add a query option for a bulk operation

2022-05-16 07:47 UTC, ttyfky commented on marketing_email.go
> +func (m MarketingEmailOp) ListStatistics(resource interface{}, option *RequestQueryOption) (*ResponseResource, error) {
I gonna make one.

2022-06-08 04:23 UTC, kk-no approved these changes
LGTM

2022-06-08 06:04 UTC, merged